#!/bin/bash
while [ "$1" != "" ]; do
    case $1 in
        -o | --output )     shift
                            RESULT=$1
                            ;;
        -i | --input )      shift
                            INPUT=$1
                            ;;
        -n | --name )       shift
                            NAME=$1
                            ;;
    esac
    shift
done

sqlite3 -separator ";" $INPUT "SELECT * FROM ${NAME}" > $RESULT

