#!/bin/bash

d=
p=
e=
add=
tmpfolder=


while [[ $1 == -* ]]
do
   case $1 in
       -h)  printf "gedi [-d] [-d2] [-p] [-t <tmpfolder] [-e] [-<java-option>] main-class [param...]\n\n -d\tStart in debug mode (server on port 8998)\n -d2\tStart in secondary debug mode (server on port 8999)\n -p\tStart cpu hprof\n -t\tspecify tmp folder\n -e\tprepend executables. before main-class\n\n"
		exit
		;;
       -d) d=" -agentlib:jdwp=transport=dt_socket,address=8998,server=y";;
       -d2) d=" -agentlib:jdwp=transport=dt_socket,address=8999,server=y";;
       -p) p=" -Xrunhprof:cpu=samples";;
       -n) exit 10;;
       -t) shift;
	   tmpfolder=" -Djava.io.tmpdir=$1"
	   mkdir -p $1
	   ;;
       -e) e=executables.;;
       -*) add="$add $1";; 
   esac
   shift;
done

/home/steven/tools/jre-9.0.4/bin/java $xp$d$p$tmpfolder$add -Xmx16394m -Xms2048m -cp `dirname $0`/gedi.jar:`dirname $0`/lib/.* $e"$@"

