#!/bin/bash
while [ "$1" != "" ]; do
    case $1 in
        -o | --output )     shift
                            RESULTSFILE=$1
                            ;;
        -n | --name )       shift
                            NAME=$1
                            ;;
    esac
    shift
done

sqlite3 $RESULTSFILE "CREATE TABLE ${NAME}(word VARCHAR, number INT)"
sqlite3 $RESULTSFILE "INSERT INTO ${NAME} VALUES ('na', 21)"
sqlite3 $RESULTSFILE "INSERT INTO ${NAME} VALUES ('batman', 1)"
